'use strict';
const el=id=>document.getElementById(id), charts={};
let watch=[], financial=[], nationwide=[], regional=[], status={}, hsNames={}, tableRows=[];
const num=v=>v==null||String(v).trim()===''?null:(Number.isFinite(Number(v))?Number(v):null);
const pct=v=>v==null?'—':`${v>0?'+':''}${v.toFixed(1)}%`;
const growth=(a,b)=>a==null||b==null||b<=0?null:(a/b-1)*100;
const monthId=s=>Number(s.slice(0,4))*12+Number(s.slice(5,7))-1;
const monthLabel=i=>`${Math.floor(i/12)}.${String(i%12+1).padStart(2,'0')}`;
function csv(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);return lines.map(line=>{let out=[],v='',quoted=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){v+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(v);v='';}else v+=c;}out.push(v);return out;});}
function records(text){const [heads,...rows]=csv(text);return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]??''])));}
async function read(path,optional=false){const r=await fetch(path+'?v='+Date.now(),{cache:'no-store'});if(optional&&r.status===404)return null;if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.text();}
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o);}
function chart(id,labels,datasets,yTitle){charts[id]?.destroy();charts[id]=new Chart(el(id),{type:'line',data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,spanGaps:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom'}},scales:{y:{title:{display:true,text:yTitle}},x:{ticks:{maxTicksLimit:16},grid:{display:false}}}}});}
function series(rows){if(!rows.length)return[];const map=new Map();for(const r of rows){if(map.has(r.month))throw Error('동일 월 중복: '+r.month);map.set(r.month,r.value);}const dates=[...map.keys()].sort();const out=[];for(let i=monthId(dates[0]);i<=monthId(dates.at(-1));i++){const month=monthLabel(i);out.push({month,value:map.get(month)??null});}return out;}
function quarterly(rows){const groups=new Map();for(const r of rows){const q=`${r.month.slice(0,4)}-Q${Math.ceil(Number(r.month.slice(5))/3)}`;if(!groups.has(q))groups.set(q,[]);groups.get(q).push(r);}return [...groups].map(([period,rs])=>{const valid=rs.filter(r=>r.value!=null);return{period,months:valid.length,value:valid.length===3?valid.reduce((s,r)=>s+r.value,0):null,actual:valid.reduce((s,r)=>s+r.value,0),rows:rs};});}
function average(rows,i){if(i<2)return null;const part=rows.slice(i-2,i+1);return part.every(x=>x.value!=null)?part.reduce((s,r)=>s+r.value,0)/3:null;}
function populateCompany(){el('company').replaceChildren();watch.filter(c=>c.category===el('category').value).forEach(c=>option(el('company'),c.id,c.name));populateHS();}
function populateHS(){const c=watch.find(c=>c.id===el('company').value);el('hs').replaceChildren();c.hs_codes.forEach(h=>option(el('hs'),h,`${hsNames[h]} · ${h}`));populateRegions();}
function populateRegions(){const c=watch.find(c=>c.id===el('company').value),hs=el('hs').value;el('region').replaceChildren();const names=[...new Set(regional.filter(r=>r.sido_code===c.sido_code&&r.hs_code===hs).map(r=>r.region))].sort();const preferred=names.filter(n=>n.includes(c.region_keyword));if(!preferred.length)option(el('region'),'missing',`${c.region_keyword} · 데이터 미확보`);[...preferred,...names.filter(n=>!preferred.includes(n))].forEach(n=>option(el('region'),n,n));option(el('region'),'national','전국 · 비교용');render();}
function render(){const c=watch.find(c=>c.id===el('company').value),hs=el('hs').value,reg=el('region').value,isNational=reg==='national';
 const national=series(nationwide.filter(r=>r['HS코드']===hs).map(r=>({month:r['월'],value:num(r['수출금액_USD'])})));
 const selected=isNational?national:series(regional.filter(r=>r.hs_code===hs&&r.sido_code===c.sido_code&&r.region===reg).map(r=>({month:r.month,value:num(r.export_amount_raw)})));
 const quarter=quarterly(selected),qm=new Map(quarter.map(r=>[r.period,r]));
 const fin=financial.filter(r=>r.company_id===c.id).sort((a,b)=>a.period.localeCompare(b.period)),fm=new Map(fin.map(r=>[r.period,r]));
 const prior=p=>`${Number(p.slice(0,4))-1}${p.slice(4)}`;
 const fy=p=>growth(num(fm.get(p)?.revenue_KRW),num(fm.get(prior(p))?.revenue_KRW));
 const qy=p=>growth(qm.get(p)?.value,qm.get(prior(p))?.value);
 el('mapping').textContent=`${c.name} (${c.id}) · ${c.region_basis}. ${c.rationale}`;
 el('coverage').textContent=`선택 지역: ${isNational?'전국':reg==='missing'?c.region_keyword:reg} | 확보 ${selected.filter(r=>r.value!=null).length}개월 | 수집 확인: ${status.updated_at??'아직 실행 결과 없음'}${status.failures?.length?' | 수집 실패 '+status.failures.length+'구간 · 기존 정상 데이터 유지':''}`;
 const i=selected.length-1,last=selected[i],map=new Map(selected.map(r=>[r.month,r.value]));
 el('yoy').textContent=pct(last?growth(last.value,map.get(monthLabel(monthId(last.month)-12))):null);el('latest').textContent=last?last.month+' · '+(isNational?'전국':reg):'지역 데이터 미확보';
 el('maYoy').textContent=pct(growth(average(selected,i),average(selected,i-12)));
 const latestFin=fin.at(-1);el('revenueYoy').textContent=latestFin?pct(fy(latestFin.period)):'—';el('revenueLatest').textContent=latestFin?latestFin.period+' · '+latestFin.status:'공시 미확보';
 const pairs=quarter.map(q=>[qy(q.period),fy(q.period)]).filter(p=>p.every(v=>v!=null));
 el('agreement').textContent=pairs.length>=8?`${(pairs.filter(p=>Math.sign(p[0])===Math.sign(p[1])).length/pairs.length*100).toFixed(0)}%`:'표본 부족';el('pairs').textContent=`동일 분기 YoY ${pairs.length}쌍 · 8쌍부터 표시`;
 el('validation').textContent=`${pairs.length}개 비교 분기 확보. ${pairs.length<12?'12개 미만으로 실적 방향 예측을 보류합니다.':'위 방향 일치율은 과거 동행성 지표입니다. 표본 외 예측 검증 전에는 매출 전망을 산출하지 않습니다.'}`;
 const base=selected.find(r=>r.value>0)?.value;const scale=v=>v==null||!base?null:v/base*100;
 el('trendTitle').textContent=(isNational?'전국':reg==='missing'?c.region_keyword:reg)+' · '+hs+' 수출 추세';
 el('trendEmpty').hidden=!!selected.length;el('trendEmpty').textContent='지역 데이터가 아직 확보되지 않았습니다. 수집 상태를 확인하거나 지역 선택에서 전국 비교를 볼 수 있습니다.';
 if(el('frequency').value==='month'){
 el('trendNote').textContent='첫 유효월=100. 월별 변동은 연속 3개월 이동평균으로 함께 확인합니다. 통화 단위의 배율 확인 전에는 지역 절대금액을 표시하지 않습니다.';
 chart('trend',selected.map(r=>r.month),[{type:'bar',label:'월별 수출 지수',data:selected.map(r=>scale(r.value)),backgroundColor:'#adc8ef'},{label:'3개월 이동평균',data:selected.map((_,i)=>scale(average(selected,i))),borderColor:'#2159a6',borderWidth:3,pointRadius:0}],'수출 지수');
 }else{const qbase=quarter.find(q=>q.value>0)?.value,sc=v=>v==null||!qbase?null:v/qbase*100;const actual=[],estimate=[];quarter.forEach((q,i)=>{const firstMonth=(Number(q.period.at(-1))-1)*3+1;const valid=q.rows.filter(r=>r.value!=null);const can=q.period===quarterly(national).at(-1)?.period&&i===quarter.length-1&&q.months>0&&q.months<3&&valid.every((r,j)=>Number(r.month.slice(5))===firstMonth+j);actual.push(q.months===3||can?sc(q.actual):null);estimate.push(can?sc(q.actual/q.months*(3-q.months)):null);});
 el('trendNote').textContent='첫 완전분기=100. 진한색은 확보분, 옅은색은 확정 월평균을 적용한 미확보 월 추정분입니다.';
 chart('trend',quarter.map(q=>q.period),[{type:'bar',label:'확보 수출',data:actual,backgroundColor:'#245bb0',stack:'sum'},{type:'bar',label:'미확보 월 추정',data:estimate,backgroundColor:'#c7d9f4',stack:'sum'}],'분기 수출 지수');charts.trend.options.scales.x.stacked=true;charts.trend.options.scales.y.stacked=true;charts.trend.update();}
 const periods=[...new Set([...quarter.map(q=>q.period),...fin.map(f=>f.period)])].sort();
 chart('comparison',periods,[{label:'수출 YoY · 완전분기',data:periods.map(qy),borderColor:'#2784b8',pointRadius:3},{label:c.name+' 매출 YoY',data:periods.map(fy),borderColor:'#27925c',pointRadius:5,borderWidth:3}],'전년 동기 대비 (%)');
 const nrows=nationwide.filter(r=>r['HS코드']===hs).sort((a,b)=>a['월'].localeCompare(b['월']));
 chart('price',nrows.map(r=>r['월']),[{label:'전국 USD/KG',data:nrows.map(r=>{const w=num(r['수출중량_KG']),v=num(r['수출금액_USD']);return w>0&&v!=null?v/w:null;}),borderColor:'#b47737',pointRadius:0}],'USD/KG');
 chart('revenue',periods,[{type:'bar',label:'연결 매출 (공시)',data:periods.map(p=>{const v=num(fm.get(p)?.revenue_KRW);return v==null?null:v/1e6;}),backgroundColor:'#70a78c'}],'백만원');
 tableRows=periods.map(p=>({period:p,months:qm.get(p)?.months??0,export_yoy:qy(p),revenue_KRW:num(fm.get(p)?.revenue_KRW),revenue_yoy:fy(p),source:fm.get(p)?.source??'',status:fm.get(p)?.status??''}));
 el('rows').replaceChildren();[...tableRows].reverse().forEach(r=>{const tr=document.createElement('tr');[r.period,r.months+'/3',pct(r.export_yoy),r.revenue_KRW==null?'—':(r.revenue_KRW/1e6).toLocaleString(undefined,{maximumFractionDigits:1}),pct(r.revenue_yoy)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});const td=document.createElement('td');if(r.source.startsWith('https://')){const a=document.createElement('a');a.href=r.source;a.textContent=r.status;a.target='_blank';a.rel='noopener';td.append(a);}tr.append(td);el('rows').append(tr);});
 el('sources').replaceChildren();c.sources.forEach((url,i)=>{const a=document.createElement('a');a.href=url;a.textContent=`선정 근거 ${i+1} `;a.target='_blank';a.rel='noopener';el('sources').append(a);});
}
el('download').onclick=()=>{const h=['period','months','export_yoy','revenue_KRW','revenue_yoy','source','status'];const data='\uFEFF'+[h.join(','),...tableRows.map(r=>h.map(k=>'"'+String(r[k]??'').replaceAll('"','""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`company-${el('company').value}-${el('hs').value}-comparison.csv`;a.click();URL.revokeObjectURL(url);};
async function init(){const [w,h,n,r,s,f]=await Promise.all([read('company_watchlist.json'),read('hs_codes.csv'),read('summary_all.csv'),read('regional_exports.csv',true),read('regional_status.json',true),read('company_financials.csv')]);watch=JSON.parse(w).companies;hsNames=Object.fromEntries(csv(h).slice(1).map(r=>[r[0],r.slice(1).join(',')]));if(watch.some(c=>c.hs_codes.some(h=>!hsNames[h])))throw Error('관심업체 HS코드가 hs_codes.csv에 없습니다.');nationwide=records(n);regional=r?records(r):[];status=s?JSON.parse(s):{};financial=records(f);el('accessNotice').hidden=!status.failures?.some(f=>/SERVICE_KEY|ACCESS_DENIED|PERMISSION|HTTP_401|HTTP_403/.test(f.error));el('companyList').replaceChildren();watch.forEach(c=>{const tr=document.createElement('tr');const count=regional.filter(r=>r.sido_code===c.sido_code&&c.hs_codes.includes(r.hs_code)&&r.region.includes(c.region_keyword)).length;[c.category,c.region_keyword,c.hs_codes.join(' / ')].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});const td=document.createElement('td'),b=document.createElement('button');b.textContent=c.name;b.onclick=()=>{el('category').value=c.category;populateCompany();el('company').value=c.id;populateHS();el('company').scrollIntoView({behavior:'smooth',block:'center'});};td.append(b);tr.append(td);const coverage=document.createElement('td');coverage.textContent=count?count+'행':'미확보';tr.append(coverage);el('companyList').append(tr);});[...new Set(watch.map(c=>c.category))].forEach(c=>option(el('category'),c,c));el('category').onchange=populateCompany;el('company').onchange=populateHS;el('hs').onchange=populateRegions;el('region').onchange=render;el('frequency').onchange=render;populateCompany();}
init().catch(e=>{el('error').hidden=false;el('error').textContent='데이터를 불러오지 못했습니다: '+e.message;});
