'use strict';
const el=id=>document.getElementById(id), charts={};
let financialCoverage={}, watchMeta={}, watch=[], financial=[], nationwide=[], regional=[], status={}, hsNames={}, tableRows=[];
const num=v=>v==null||String(v).trim()===''?null:(Number.isFinite(Number(v))?Number(v):null);
const opm=r=>{const revenue=num(r?.revenue_KRW),profit=num(r?.operating_profit_KRW);return revenue>0&&profit!=null?profit/revenue*100:null;};
const pct=v=>v==null?'—':`${v>0?'+':''}${v.toFixed(1)}%`;
const growth=(a,b)=>a==null||b==null||b<=0?null:(a/b-1)*100;
const monthId=s=>Number(s.slice(0,4))*12+Number(s.slice(5,7))-1;
const monthLabel=i=>`${Math.floor(i/12)}.${String(i%12+1).padStart(2,'0')}`;
function csv(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);return lines.map(line=>{let out=[],v='',quoted=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){v+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(v);v='';}else v+=c;}out.push(v);return out;});}
function records(text){const [heads,...rows]=csv(text);return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]??''])));}
async function read(path,optional=false){const r=await fetch(path+'?v='+Date.now(),{cache:'no-store'});if(optional&&r.status===404)return null;if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.text();}
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o);}
function chart(id,labels,datasets,yTitle,extra={}){charts[id]?.destroy();const scales={y:{title:{display:true,text:yTitle}},x:{ticks:{maxTicksLimit:16},grid:{display:false}},...(extra.scales||{})};const plugins={legend:{position:'bottom'},...(extra.plugins||{})};charts[id]=new Chart(el(id),{type:'line',data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,spanGaps:false,interaction:{mode:'index',intersect:false},...extra,plugins,scales}});}
function series(rows){if(!rows.length)return[];const map=new Map();for(const r of rows){if(map.has(r.month))throw Error('동일 월 중복: '+r.month);map.set(r.month,r.value);}const dates=[...map.keys()].sort();const out=[];for(let i=monthId(dates[0]);i<=monthId(dates.at(-1));i++){const month=monthLabel(i);out.push({month,value:map.get(month)??null});}return out;}
function quarterly(rows){const groups=new Map();for(const r of rows){const q=`${r.month.slice(0,4)}-Q${Math.ceil(Number(r.month.slice(5))/3)}`;if(!groups.has(q))groups.set(q,[]);groups.get(q).push(r);}return [...groups].map(([period,rs])=>{const valid=rs.filter(r=>r.value!=null);return{period,months:valid.length,value:valid.length===3?valid.reduce((s,r)=>s+r.value,0):null,actual:valid.reduce((s,r)=>s+r.value,0),rows:rs};});}
function average(rows,i){if(i<2)return null;const part=rows.slice(i-2,i+1);return part.every(x=>x.value!=null)?part.reduce((s,r)=>s+r.value,0)/3:null;}
function populateCompany(){el('company').replaceChildren();watch.filter(c=>c.category===el('category').value).forEach(c=>option(el('company'),c.id,c.name));populateHS();}
function populateHS(){const c=watch.find(c=>c.id===el('company').value);el('hs').replaceChildren();c.hs_codes.forEach(h=>option(el('hs'),h,`${hsNames[h]} · ${h}`));populateRegions();}
function queryHS(c,h){return c.regional_hs?c.regional_hs[h]:(h.length===6?h:null);}
function sites(c,h){return (c.sites||[c]).filter(s=>!h||!s.hs_codes||s.hs_codes.includes(h));}
function regionRows(c,h){const q=queryHS(c,h);return regional.filter(r=>r.hs_code===q&&sites(c,h).some(s=>s.sido_code===r.sido_code&&r.region.includes(s.region_keyword)));}
function populateRegions(){const c=watch.find(c=>c.id===el('company').value),h=el('hs').value;el('region').replaceChildren();const rows=regionRows(c,h),seen=new Set();for(const r of rows){const key=r.sido_code+'|'+r.region;if(!seen.has(key)){option(el('region'),key,r.region);seen.add(key);}}if(!seen.size)option(el('region'),'missing',queryHS(c,h)?'대상 지역 데이터 미확보':'HS4 지역 조회 미지원');option(el('region'),'national','전국 · 관리 품목 비교용');render();}
function render(){const c=watch.find(c=>c.id===el('company').value),hs=el('hs').value,reg=el('region').value,isNational=reg==='national',query=queryHS(c,hs),[sido,regionName]=reg.split('|');
 const national=series(nationwide.filter(r=>r['HS코드']===hs).map(r=>({month:r['월'],value:num(r['수출금액_USD'])})));
 const selected=isNational?national:series(regional.filter(r=>r.hs_code===query&&r.sido_code===sido&&r.region===regionName).map(r=>({month:r.month,value:num(r.export_amount_raw)})));
 const quarter=quarterly(selected),qm=new Map(quarter.map(r=>[r.period,r]));
 const fin=financial.filter(r=>r.company_id===c.id).sort((a,b)=>a.period.localeCompare(b.period)),fm=new Map(fin.map(r=>[r.period,r]));
 const prior=p=>`${Number(p.slice(0,4))-1}${p.slice(4)}`;
 const fy=p=>growth(num(fm.get(p)?.revenue_KRW),num(fm.get(prior(p))?.revenue_KRW));
 const qy=p=>growth(qm.get(p)?.value,qm.get(prior(p))?.value);
 el('scopeNotice').textContent=isNational?'전국 비교: 관리 품목 '+hs+' 데이터입니다. 지역 상위품목 지표와 범위가 다를 수 있습니다.':!query?'HS 4자리 총괄은 이 지역 API에서 조회할 수 없습니다. 관련 세부 관리 품목을 선택하세요.':query!==hs?'관리 HS '+hs+' → 지역 조회 HS '+query+' 상위 품목군 참고지표. 세부 품목 전용 수출이 아닙니다.':'지역 조회 HS '+query+' · 해당 지역 품목군 전체. 개별 업체 수출액이 아닙니다.';
 const peers=watch.filter(x=>x.id!==c.id&&x.hs_codes.some(h=>queryHS(x,h)===query&&sites(x,h).some(t=>t.sido_code===sido&&regionName?.includes(t.region_keyword))));el('sharedCandidates').textContent=isNational?'':peers.length?'동일 지역·HS 통계를 공유하는 후보: '+peers.map(x=>x.name).join(', ')+' — 업체별 기여도 분리 불가.':'목록 내 동일 지역·HS 후보가 없더라도 해당 업체의 독점 수출을 뜻하지 않습니다.';
 el('mapping').textContent=`${c.name} (${c.id}) · ${c.region_basis}. ${c.rationale}`;
 el('coverage').textContent=`선택 지역: ${isNational?'전국':reg==='missing'?sites(c,hs).map(t=>t.region_keyword).join(' · '):regionName} | 확보 ${selected.filter(r=>r.value!=null).length}개월 | 수집 확인: ${status.updated_at??'아직 실행 결과 없음'}${status.failures?.length?' | 수집 실패 '+status.failures.length+'구간 · 기존 정상 데이터 유지':''}`;
 const i=selected.length-1,last=selected[i],map=new Map(selected.map(r=>[r.month,r.value]));
 el('yoy').textContent=pct(last?growth(last.value,map.get(monthLabel(monthId(last.month)-12))):null);el('latest').textContent=last?last.month+' · '+(isNational?'전국':regionName):'지역 데이터 미확보';
 el('maYoy').textContent=pct(growth(average(selected,i),average(selected,i-12)));
 const latestFin=[...fin].reverse().find(r=>fy(r.period)!=null)||fin.at(-1);el('revenueYoy').textContent=latestFin?pct(fy(latestFin.period)):'—';el('revenueLatest').textContent=latestFin?(fy(latestFin.period)!=null?latestFin.period+' · '+latestFin.status:latestFin.period+' · 전년동기 공시 미확보'):'공시 미확보';
 const pairs=quarter.map(q=>[qy(q.period),fy(q.period)]).filter(p=>p.every(v=>v!=null));
 const agree=pairs.length?pairs.filter(p=>Math.sign(p[0])===Math.sign(p[1])).length/pairs.length*100:null;
 const confidence=pairs.length>=8?'참고 가능':pairs.length>=3?'초기 신호':'표본 부족';
 el('agreement').textContent=agree==null?'표본 부족':`${agree.toFixed(0)}% · ${confidence}`;
 el('pairs').textContent=`동일 분기 YoY ${pairs.length}쌍 · 3쌍부터 초기 신호, 8쌍부터 참고 가능`;
 el('validation').textContent=pairs.length<3?`${pairs.length}개 비교 분기 확보. 방향 일치율을 표시하기에는 표본이 부족합니다.`:pairs.length<8?`${pairs.length}개 비교 분기의 초기 신호입니다. 방향 일치율은 참고용으로만 표시하며 매출 예측에는 사용하지 않습니다.`:`${pairs.length}개 비교 분기의 과거 동행성 지표입니다. 표본 외 예측 검증 전에는 매출 전망을 산출하지 않습니다.`;
 const base=selected.find(r=>r.value>0)?.value;const scale=v=>v==null||!base?null:v/base*100;
 el('trendTitle').textContent=(isNational?'전국':reg==='missing'?sites(c,hs).map(t=>t.region_keyword).join(' · '):regionName)+' · '+(isNational?hs:query||hs)+' 수출 추세';
 el('trendEmpty').hidden=!!selected.length;el('trendEmpty').textContent='지역 데이터가 아직 확보되지 않았습니다. 수집 상태를 확인하거나 지역 선택에서 전국 비교를 볼 수 있습니다.';
 if(el('frequency').value==='month'){
 el('trendNote').textContent='첫 유효월=100. 월별 변동은 연속 3개월 이동평균으로 함께 확인합니다. 통화 단위의 배율 확인 전에는 지역 절대금액을 표시하지 않습니다.';
 chart('trend',selected.map(r=>r.month),[{type:'bar',label:'월별 수출 지수',data:selected.map(r=>scale(r.value)),backgroundColor:'#adc8ef'},{label:'3개월 이동평균',data:selected.map((_,i)=>scale(average(selected,i))),borderColor:'#2159a6',borderWidth:3,pointRadius:0}],'수출 지수');
 }else{const qbase=quarter.find(q=>q.value>0)?.value,sc=v=>v==null||!qbase?null:v/qbase*100;const actual=[],estimate=[];quarter.forEach((q,i)=>{const firstMonth=(Number(q.period.at(-1))-1)*3+1;const valid=q.rows.filter(r=>r.value!=null);const can=q.period===quarterly(national).at(-1)?.period&&i===quarter.length-1&&q.months>0&&q.months<3&&valid.every((r,j)=>Number(r.month.slice(5))===firstMonth+j);actual.push(q.months===3||can?sc(q.actual):null);estimate.push(can?sc(q.actual/q.months*(3-q.months)):null);});
 el('trendNote').textContent='첫 완전분기=100. 진한색은 확보분, 옅은색은 확정 월평균을 적용한 미확보 월 추정분입니다.';
 chart('trend',quarter.map(q=>q.period),[{type:'bar',label:'확보 수출',data:actual,backgroundColor:'#245bb0',stack:'sum'},{type:'bar',label:'미확보 월 추정',data:estimate,backgroundColor:'#c7d9f4',stack:'sum'}],'분기 수출 지수');charts.trend.options.scales.x.stacked=true;charts.trend.options.scales.y.stacked=true;charts.trend.update();}
 const periods=[...new Set([...quarter.map(q=>q.period),...fin.map(f=>f.period)])].sort();
 const monthlyMap=new Map(selected.map(r=>[r.month,r.value]));
 const monthlyYoy=p=>growth(monthlyMap.get(p),monthlyMap.get(monthLabel(monthId(p)-12)));
 const monthlyMode=el('frequency').value==='month';
 const comparisonPeriods=monthlyMode?selected.map(r=>r.month):periods;
 chart('comparison',comparisonPeriods,[{label:monthlyMode?'수출 YoY · 월별':'수출 YoY · 완전분기',data:comparisonPeriods.map(monthlyMode?monthlyYoy:qy),borderColor:'#2784b8',pointRadius:3},{label:monthlyMode?'공시 매출 YoY · 분기 자료':'매출 YoY',data:comparisonPeriods.map(monthlyMode?()=>null:fy),borderColor:'#27925c',pointRadius:5,borderWidth:3,spanGaps:true}],'전년 동기 대비 (%)');
 if(el('comparisonNote'))el('comparisonNote').textContent=monthlyMode?'월별 선택: 수출 YoY는 동일 월 전년 대비로 표시합니다. 공시 매출은 분기 자료만 있어 월별 그래프에는 표시하지 않습니다.':'분기별 선택: 수출 YoY와 회사 공시 매출 YoY를 동일 분기 기준으로 비교합니다.';
 const amountPeriods=monthlyMode?selected.map(r=>r.month):quarter.map(q=>q.period);
 const exportAmounts=monthlyMode?selected.map(r=>r.value):quarter.map(q=>q.value);
 const revenueAmounts=monthlyMode?amountPeriods.map(p=>{const q=`${p.slice(0,4)}-Q${Math.ceil(Number(p.slice(5))/3)}`;const v=num(fm.get(q)?.revenue_KRW);return Number(p.slice(5))%3===0&&v!=null?v/1e8:null;}):amountPeriods.map(p=>{const v=num(fm.get(p)?.revenue_KRW);return v==null?null:v/1e8;});
 chart('amountComparison',amountPeriods,[{label:'지역 수출액 · USD',data:exportAmounts,borderColor:'#2784b8',pointRadius:2,yAxisID:'yExport'},{label:c.name+' 매출액 · 억원',data:revenueAmounts,borderColor:'#d97835',pointRadius:4,borderWidth:3,spanGaps:true,yAxisID:'yRevenue'}],'금액',{spanGaps:true,scales:{y:{display:false},yExport:{type:'linear',position:'left',title:{display:true,text:'수출액 (USD · 신고미화금액)'},ticks:{callback:v=>Number(v).toLocaleString()}},yRevenue:{type:'linear',position:'right',title:{display:true,text:'회사 매출액 (억원)'},grid:{drawOnChartArea:false},ticks:{callback:v=>Number(v).toLocaleString()}}},plugins:{tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${Number(ctx.parsed.y).toLocaleString()} ${ctx.dataset.yAxisID==='yRevenue'?'억원':'USD'}`}}}});
 if(el('amountNote'))el('amountNote').textContent=monthlyMode?'좌측 수출액은 관세청 API 신고미화금액(USD), 우측 매출액은 공시 원화 매출을 억원으로 환산했습니다. 매출선은 확보된 공시 시점을 연결하며 누락 구간은 추정하지 않습니다.':'좌측 수출액은 관세청 API 신고미화금액(USD), 우측 매출액은 공시 원화 매출을 억원으로 환산했습니다. 매출선은 확보된 공시 시점을 연결하며 누락 구간은 추정하지 않습니다.';
 const domesticAmounts=monthlyMode?amountPeriods.map(p=>{const q=`${p.slice(0,4)}-Q${Math.ceil(Number(p.slice(5))/3)}`;const v=num(fm.get(q)?.domestic_revenue_KRW);return Number(p.slice(5))%3===0&&v!=null?v/1e8:null;}):amountPeriods.map(p=>{const v=num(fm.get(p)?.domestic_revenue_KRW);return v==null?null:v/1e8;});
 chart('domesticComparison',amountPeriods,[{label:'지역 수출액 · USD',data:exportAmounts,borderColor:'#2784b8',pointRadius:2,yAxisID:'yExport'},{label:c.name+' 국내법인 별도 매출 · 억원',data:domesticAmounts,borderColor:'#008b87',pointRadius:4,borderWidth:3,spanGaps:true,yAxisID:'yRevenue'}],'금액',{spanGaps:true,scales:{y:{display:false},yExport:{type:'linear',position:'left',title:{display:true,text:'수출액 (USD · 신고미화금액)'},ticks:{callback:v=>Number(v).toLocaleString()}},yRevenue:{type:'linear',position:'right',title:{display:true,text:'국내법인 별도 매출 (억원)'},grid:{drawOnChartArea:false},ticks:{callback:v=>Number(v).toLocaleString()}}},plugins:{tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${Number(ctx.parsed.y).toLocaleString()} ${ctx.dataset.yAxisID==='yRevenue'?'억원':'USD'}`}}}});
 if(el('domesticAmountNote')&&!domesticAmounts.some(v=>v!=null))el('domesticAmountNote').textContent='국내공장 매출 proxy · 국내법인 별도재무제표 기준. 현재 확인된 별도 공시값이 없어 선은 공란으로 유지됩니다. 연결매출과 혼용하지 않습니다.';
 const nrows=nationwide.filter(r=>r['HS코드']===hs).sort((a,b)=>a['월'].localeCompare(b['월']));
 chart('price',nrows.map(r=>r['월']),[{label:'전국 USD/KG',data:nrows.map(r=>{const w=num(r['수출중량_KG']),v=num(r['수출금액_USD']);return w>0&&v!=null?v/w:null;}),borderColor:'#b47737',pointRadius:0}],'USD/KG');
 const earningsPeriods=[];const qi=p=>Number(p.slice(0,4))*4+Number(p.at(-1))-1;
 const rangeStart=financialCoverage.start_period||fin[0]?.period,rangeEnd=financialCoverage.end_period||fin.at(-1)?.period;
 if(rangeStart&&rangeEnd)for(let q=qi(rangeStart);q<=qi(rangeEnd);q++)earningsPeriods.push(Math.floor(q/4)+'-Q'+(q%4+1));
 const earningsMissing=earningsPeriods.filter(p=>num(fm.get(p)?.revenue_KRW)==null||opm(fm.get(p))==null);
 el('earningsTitle').textContent=c.name+' · 분기 매출·OPM';
 el('earningsNote').textContent=(rangeStart?rangeStart+' ~ '+rangeEnd+' · ':'')+'연결 분기 실적 · '+(earningsPeriods.length-earningsMissing.length)+'/'+earningsPeriods.length+'분기 확보 · '+(earningsMissing.length?'미확보: '+earningsMissing.join(', '):'누락 없음')+'. OPM = 영업이익 ÷ 매출 × 100. 4분기는 연간−3분기 누적으로 산출하며 아래 표에 두 공시 원문을 표시합니다.';
 chart('revenue',earningsPeriods,[{type:'bar',label:'매출액 (좌 · 억원)',data:earningsPeriods.map(p=>{const v=num(fm.get(p)?.revenue_KRW);return v==null?null:v/1e8;}),backgroundColor:'#b7bdc4',yAxisID:'y',order:1,maxBarThickness:46},{type:'line',label:'OPM (우 · %)',data:earningsPeriods.map(p=>opm(fm.get(p))),borderColor:'#008b87',backgroundColor:'#008b87',borderWidth:3,pointRadius:4,yAxisID:'yOPM',order:0,spanGaps:false}],'매출액 (억원)',{scales:{y:{type:'linear',position:'left',beginAtZero:true,title:{display:true,text:'매출액 (억원)'}},yOPM:{type:'linear',position:'right',title:{display:true,text:'OPM (%)'},grid:{drawOnChartArea:false},ticks:{callback:v=>v+'%'}}},plugins:{tooltip:{callbacks:{label:ctx=>ctx.dataset.yAxisID==='yOPM'?'OPM: '+ctx.parsed.y.toFixed(2)+'%':'매출액: '+ctx.parsed.y.toLocaleString(undefined,{maximumFractionDigits:1})+'억원'}}}});

 tableRows=periods.map(p=>({period:p,months:qm.get(p)?.months??0,export_yoy:qy(p),revenue_KRW:num(fm.get(p)?.revenue_KRW),revenue_yoy:fy(p),operating_profit_KRW:num(fm.get(p)?.operating_profit_KRW),opm_pct:opm(fm.get(p)),source:fm.get(p)?.source??'',source_secondary:fm.get(p)?.source_secondary??'',status:fm.get(p)?.status??''}));
 el('rows').replaceChildren();[...tableRows].reverse().forEach(r=>{const tr=document.createElement('tr');[r.period,r.months+'/3',pct(r.export_yoy),r.revenue_KRW==null?'—':(r.revenue_KRW/1e8).toLocaleString(undefined,{maximumFractionDigits:1}),pct(r.revenue_yoy),r.operating_profit_KRW==null?'—':(r.operating_profit_KRW/1e8).toLocaleString(undefined,{maximumFractionDigits:1}),pct(r.opm_pct)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});const td=document.createElement('td');if(r.source.startsWith('https://')){const a=document.createElement('a');a.href=r.source;a.textContent=r.status;a.target='_blank';a.rel='noopener';td.append(a);}if(r.source_secondary?.startsWith('https://')){const a=document.createElement('a');a.href=r.source_secondary;a.textContent=' · 3분기 누적 원문';a.target='_blank';a.rel='noopener';td.append(a);}tr.append(td);el('rows').append(tr);});
 el('sources').replaceChildren();c.sources.forEach((url,i)=>{const a=document.createElement('a');a.href=url;a.textContent=`선정 근거 ${i+1} `;a.target='_blank';a.rel='noopener';el('sources').append(a);});
}
el('download').onclick=()=>{const h=['period','months','export_yoy','revenue_KRW','revenue_yoy','operating_profit_KRW','opm_pct','source','source_secondary','status'];const data='\uFEFF'+[['company_id','managed_hs','query_hs','region',...h].join(','),...tableRows.map(r=>[el('company').value,el('hs').value,queryHS(watch.find(c=>c.id===el('company').value),el('hs').value)||'',el('region').value,...h.map(k=>r[k]??'')].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`company-${el('company').value}-${el('hs').value}-comparison.csv`;a.click();URL.revokeObjectURL(url);};
function cell(tr,text){const td=document.createElement('td');td.textContent=text;tr.append(td);return td;}
function choose(c,h){el('category').value=c.category;populateCompany();el('company').value=c.id;populateHS();if(h){el('hs').value=h;populateRegions();}el('company').scrollIntoView({behavior:'smooth',block:'center'});}
function companyButton(c,h){const b=document.createElement('button');b.textContent=c.name;b.onclick=()=>choose(c,h);return b;}
function renderUniverse(){if(!el('companyList'))return;const term=(el('companySearch')?.value||'').trim().toLowerCase(),cat=el('industryFilter')?.value||'';el('companyList').replaceChildren();const filtered=watch.filter(c=>(!cat||c.category===cat)&&[c.name,c.id,c.category,...sites(c).map(s=>s.region_keyword),...c.hs_codes,...c.hs_codes.map(h=>hsNames[h])].join(' ').toLowerCase().includes(term));for(const c of filtered){const tr=document.createElement('tr');cell(tr,c.category);const name=cell(tr,'');name.append(companyButton(c));const id=document.createElement('small');id.textContent=c.id==='LS-CABLE'?'비상장 제조사':c.id;name.append(id);cell(tr,[...new Set(sites(c).map(s=>s.region_keyword))].join(' · '));cell(tr,c.hs_codes.map(h=>hsNames[h]+' ('+h+')').join(' / '));const logical=c.hs_codes.find(h=>queryHS(c,h)),q=logical?queryHS(c,logical):null;const site=logical?sites(c,logical)[0]:null;const rs=site?regionRows(c,logical).filter(r=>r.sido_code===site.sido_code&&r.region.includes(site.region_keyword)).sort((a,b)=>a.month.localeCompare(b.month)):[];const regions=[...new Set(rs.map(r=>r.region))];const last=regions.length===1?rs.at(-1):null,prev=last?rs.find(r=>r.month===monthLabel(monthId(last.month)-12)):null;cell(tr,last?pct(growth(num(last.export_amount_raw),num(prev?.export_amount_raw)))+' · '+last.month+' · '+last.region+' · HS'+q:'미확보 / 대표지역 단일 시계열 확인 필요');const count=new Set(c.hs_codes.flatMap(h=>regionRows(c,h).map(r=>[r.month,r.hs_code,r.sido_code,r.region].join('|')))).size;cell(tr,(c.hs_codes.some(h=>h.length===10)?'HS6 상위 품목군 포함':'HS6 품목군')+' · '+count+'행');const coverage=financialCoverage.companies?.find(r=>r.company_id===c.id);cell(tr,coverage?coverage.complete_quarters+'/'+coverage.expected_quarters+'분기 · '+(coverage.status==='complete'?'누락 없음':coverage.status==='not_collected'?'실적 미확보':'누락 '+coverage.missing_periods.join(', ')):'실적 범위 미확인');const td=cell(tr,'');const link=document.createElement('a');link.href=c.sources[0];link.textContent='공식 근거';link.target='_blank';link.rel='noopener';td.append(link);el('companyList').append(tr);}if(el('listCount'))el('listCount').textContent=filtered.length+' / '+watch.length+'개 업체 표시 · YoY는 표에 적힌 대표 지역·품목군의 값입니다.';}
function renderCoverage(){if(!el('hsCoverage'))return;el('hsCoverage').replaceChildren();for(const [h,name] of Object.entries(hsNames)){const tr=document.createElement('tr');cell(tr,name+' · '+h);const cs=watch.filter(c=>c.hs_codes.includes(h));cell(tr,h.length===4?'직접 조회 미지원':h.slice(0,6)+(h.length===10?' · 상위 품목군':''));const td=cell(tr,'');cs.forEach(c=>{td.append(companyButton(c,h),document.createTextNode(' '));});if(!cs.length)td.textContent='확인된 연결 없음';cell(tr,watchMeta.unmapped_notes?.[h]||(h.length===4?'총괄을 임의의 세부 코드로 대체하지 않습니다.':h.startsWith('300249')||h.startsWith('854143')?'2022년 이전 지역 시계열 미연결. 월간 대시보드의 과거 HS 연결은 유지.':h.length===10?'제품·생산지역 근거로 연결한 후보. 개별 수출 신고코드·점유율 미확인.':'제품·생산지역 근거로 연결한 후보. 지역 통계에는 타 업체가 포함됩니다.'));el('hsCoverage').append(tr);}}
async function init(){const [w,h,n,r,s,f,fc]=await Promise.all([read('company_watchlist.json'),read('hs_codes.csv'),read('summary_all.csv'),read('regional_exports.csv',true),read('regional_status.json',true),read('company_financials.csv'),read('company_financial_coverage.json',true)]);watchMeta=JSON.parse(w);watch=watchMeta.companies;hsNames=Object.fromEntries(csv(h).slice(1).map(r=>[r[0],r.slice(1).join(',')]));if(watch.some(c=>c.hs_codes.some(h=>!hsNames[h])))throw Error('관심업체 HS코드가 hs_codes.csv에 없습니다.');nationwide=records(n);regional=r?records(r):[];status=s?JSON.parse(s):{};financial=records(f);financialCoverage=fc?JSON.parse(fc):{};if(el('financialCoverageSummary')){const cs=financialCoverage.companies||[];el('financialCoverageSummary').textContent=cs.length?'실적 점검 범위 '+financialCoverage.start_period+' ~ '+financialCoverage.end_period+' · 연속 분기 확보 '+cs.filter(c=>c.status==='complete').length+'/'+cs.length+'개 업체. 나머지 업체의 미확보 상태는 아래 목록에 표시합니다. 확인일 '+financialCoverage.reviewed_at:'실적 수집 범위 확인 필요';}el('accessNotice').hidden=!status.failures?.some(f=>/SERVICE_KEY|ACCESS_DENIED|PERMISSION|HTTP_401|HTTP_403/.test(f.error));const categories=[...new Set(watch.map(c=>c.category))];categories.forEach(c=>{option(el('category'),c,c);if(el('industryFilter'))option(el('industryFilter'),c,c);});if(el('universeSummary'))el('universeSummary').textContent=watch.length+'개 업체 · '+watch.flatMap(c=>sites(c)).length+'개 업체-생산지역 연결 · '+new Set(watch.flatMap(c=>c.hs_codes)).size+'/'+Object.keys(hsNames).length+'개 관리 품목에 후보 연결';if(el('reviewDate'))el('reviewDate').textContent=watchMeta.reviewed_at||'2026-10-07';if(el('companySearch'))el('companySearch').oninput=renderUniverse;if(el('industryFilter'))el('industryFilter').onchange=renderUniverse;renderUniverse();renderCoverage();el('category').onchange=populateCompany;el('company').onchange=populateHS;el('hs').onchange=populateRegions;el('region').onchange=render;el('frequency').onchange=render;populateCompany();}
init().catch(e=>{el('error').hidden=false;el('error').textContent='데이터를 불러오지 못했습니다: '+e.message;});

