'use strict';
const el=id=>document.getElementById(id), charts={};
let breaks=[],backlogCoverage={}, financialCoverage={}, watchMeta={}, watch=[], financial=[], domesticFinancial=[], backlog=[], nationwide=[], regional=[], status={}, hsNames={}, tableRows=[];
const num=v=>v==null||String(v).trim()===''?null:(Number.isFinite(Number(v))?Number(v):null);
const opm=r=>{const revenue=num(r?.revenue_KRW),profit=num(r?.operating_profit_KRW);return revenue>0&&profit!=null?profit/revenue*100:null;};
const pct=v=>v==null?'—':`${v>0?'+':''}${v.toFixed(1)}%`;
const growth=(a,b)=>a==null||b==null||b<=0?null:(a/b-1)*100;
const pearson=(pairs)=>{if(pairs.length<2)return null;const xs=pairs.map(p=>p[0]),ys=pairs.map(p=>p[1]),mx=xs.reduce((a,b)=>a+b,0)/xs.length,my=ys.reduce((a,b)=>a+b,0)/ys.length;const nume=xs.reduce((s,x,i)=>s+(x-mx)*(ys[i]-my),0),dx=Math.sqrt(xs.reduce((s,x)=>s+(x-mx)**2,0)),dy=Math.sqrt(ys.reduce((s,y)=>s+(y-my)**2,0));return dx&&dy?nume/(dx*dy):null;};
const corrText=(r,n)=>r==null?'상관계수 산출 불가 · 완전분기 '+n+'개 미만 또는 값 변동 없음':`피어슨 상관계수 r = ${r.toFixed(2)} · 완전분기 ${n}개 · 금액 수준 비교`;
const monthId=s=>Number(s.slice(0,4))*12+Number(s.slice(5,7))-1;
const monthLabel=i=>`${Math.floor(i/12)}.${String(i%12+1).padStart(2,'0')}`;
function csv(text){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);return lines.map(line=>{let out=[],v='',quoted=false;for(let i=0;i<line.length;i++){let c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){v+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){out.push(v);v='';}else v+=c;}out.push(v);return out;});}
function records(text){const [heads,...rows]=csv(text);return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]??''])));}
async function read(path,optional=false){const r=await fetch(path+'?v='+Date.now(),{cache:'no-store'});if(optional&&r.status===404)return null;if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);return r.text();}
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o);}
function chart(id,labels,datasets,yTitle,extra={}){charts[id]?.destroy();const scales={y:{title:{display:true,text:yTitle}},x:{ticks:{maxTicksLimit:16},grid:{display:false}},...(extra.scales||{})};const plugins={legend:{position:'bottom'},...(extra.plugins||{})};charts[id]=new Chart(el(id),{type:'line',data:{labels,datasets},options:{responsive:true,maintainAspectRatio:false,spanGaps:false,interaction:{mode:'index',intersect:false},...extra,plugins,scales}});}
function correlationChart(id,pairs,xTitle,yTitle){charts[id]?.destroy();const points=pairs.map(p=>({x:p[0],y:p[1]}));let line=[];if(points.length>=2){const mx=points.reduce((s,p)=>s+p.x,0)/points.length,my=points.reduce((s,p)=>s+p.y,0)/points.length;const denominator=points.reduce((s,p)=>s+(p.x-mx)**2,0);const slope=denominator?points.reduce((s,p)=>s+(p.x-mx)*(p.y-my),0)/denominator:0;const intercept=my-slope*mx;const min=Math.min(...points.map(p=>p.x)),max=Math.max(...points.map(p=>p.x));line=[{x:min,y:slope*min+intercept},{x:max,y:slope*max+intercept}];}charts[id]=new Chart(el(id),{type:'scatter',data:{datasets:[{label:'분기별 관측값',type:'scatter',data:points,backgroundColor:'#2784b8',borderColor:'#2784b8',pointRadius:5,order:1},{label:'선형 추세선',type:'line',data:line,borderColor:'#d97835',borderWidth:3,borderDash:[6,4],pointRadius:0,pointHoverRadius:0,showLine:true,tension:0,fill:false,order:0}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'nearest',intersect:false},plugins:{legend:{position:'bottom'},tooltip:{callbacks:{label:ctx=>`수출액 ${Number(ctx.parsed.x).toLocaleString()} USD · 매출 ${Number(ctx.parsed.y).toLocaleString(undefined,{maximumFractionDigits:1})}억원`}}},scales:{x:{type:'linear',title:{display:true,text:xTitle},ticks:{callback:v=>Number(v).toLocaleString()}},y:{title:{display:true,text:yTitle},beginAtZero:true,ticks:{callback:v=>Number(v).toLocaleString()}}}}});}
function series(rows){if(!rows.length)return[];const map=new Map();for(const r of rows){if(map.has(r.month))throw Error('동일 월 중복: '+r.month);map.set(r.month,r.value);}const dates=[...map.keys()].sort();const out=[];for(let i=monthId(dates[0]);i<=monthId(dates.at(-1));i++){const month=monthLabel(i);out.push({month,value:map.get(month)??null});}return out;}
function quarterly(rows){const groups=new Map();for(const r of rows){const q=`${r.month.slice(0,4)}-Q${Math.ceil(Number(r.month.slice(5))/3)}`;if(!groups.has(q))groups.set(q,[]);groups.get(q).push(r);}return [...groups].map(([period,rs])=>{const valid=rs.filter(r=>r.value!=null);return{period,months:valid.length,value:valid.length===3?valid.reduce((s,r)=>s+r.value,0):null,actual:valid.reduce((s,r)=>s+r.value,0),rows:rs};});}
function average(rows,i){if(i<2)return null;const part=rows.slice(i-2,i+1);return part.every(x=>x.value!=null)?part.reduce((s,r)=>s+r.value,0)/3:null;}
function populateCompany(){el('company').replaceChildren();watch.filter(c=>c.category===el('category').value).forEach(c=>option(el('company'),c.id,c.name));populateHS();}
function populateHS(){const c=watch.find(c=>c.id===el('company').value);el('hs').replaceChildren();{const a=allSitesHS(c);if(a)option(el('hs'),a,'업체 전체 · 사업장 합산 (HS '+a.slice(4)+')');}c.hs_codes.forEach(h=>option(el('hs'),h,`${hsNames[h]} · ${h}`));{const q=[...el('hs').options].find(o=>queryHS(c,o.value));if(q)el('hs').value=q.value;}populateRegions();}
function allSitesHS(c){const qs=c.hs_codes.map(h=>c.regional_hs?c.regional_hs[h]:(h.length===6?h:null)).filter(Boolean),u=[...new Set(qs)];const multi=(c.sites||[]).length>1&&(c.sites||[]).some(s=>s.hs_codes);return u.length===1&&multi?'ALL:'+u[0]:null;}
function natHS(c,h){return h.startsWith('ALL:')?c.hs_codes[0]:h;}
function queryHS(c,h){if(h.startsWith('ALL:'))return h.slice(4);return c.regional_hs?c.regional_hs[h]:(h.length===6?h:null);}
function sites(c,h){return (c.sites||[c]).filter(s=>!h||h.startsWith('ALL:')||!s.hs_codes||s.hs_codes.includes(h));}
function regionRows(c,h){const q=queryHS(c,h);return regional.filter(r=>r.hs_code===q&&sites(c,h).some(s=>s.sido_code===r.sido_code&&r.region.includes(s.region_keyword)));}
function comboRows(c,h){const rs=regionRows(c,h),keys=[...new Set(rs.map(r=>r.sido_code+'|'+r.region))],by=new Map();for(const r of rs){if(!by.has(r.month))by.set(r.month,new Map());by.get(r.month).set(r.sido_code+'|'+r.region,num(r.export_amount_raw));}return{keys,rows:[...by].map(([month,m])=>({month,value:keys.every(k=>m.get(k)!=null)?keys.reduce((s,k)=>s+m.get(k),0):null})).sort((a,b)=>a.month.localeCompare(b.month))};}

// 진행 중인 분기의 미수집 월을 같은 분기 확보월의 전년 대비 증감률로 추정합니다.
function estimateQuarter(selected){const valid=selected.filter(r=>r.value!=null);if(!valid.length)return null;const last=valid.at(-1),y=Number(last.month.slice(0,4)),m=Number(last.month.slice(5)),qn=Math.ceil(m/3),first=(qn-1)*3+1;if(m%3===0)return null;
 const map=new Map(selected.map(r=>[r.month,r.value])),lab=k=>`${y}.${String(k).padStart(2,'0')}`,prev=k=>`${y-1}.${String(k).padStart(2,'0')}`;
 const have=[];for(let k=first;k<=m;k++){const v=map.get(lab(k));if(v==null)return null;have.push(k);}
 const missing=[];for(let k=m+1;k<=first+2;k++)missing.push(k);
 const cur=have.reduce((s,k)=>s+map.get(lab(k)),0),base=have.reduce((s,k)=>s+(map.get(prev(k))??NaN),0);
 let ratio=null,method;const est=[];
 if(Number.isFinite(base)&&base>0&&missing.every(k=>map.get(prev(k))!=null)){ratio=cur/base;method='yoy';missing.forEach(k=>est.push({month:lab(k),value:map.get(prev(k))*ratio}));}
 else{method='avg';missing.forEach(k=>est.push({month:lab(k),value:cur/have.length}));}
 const actual=cur,total=cur+est.reduce((s,r)=>s+r.value,0);
 return{period:`${y}-Q${qn}`,endMonth:lab(first+2),have:have.map(lab),est,actual,total,ratio,method};}
// 완전분기 수출액-매출 선형회귀로 매출을 예상하고, 최근 분기를 순차 백테스트해 오차를 함께 보여줍니다.
function linfit(pairs){const n=pairs.length,mx=pairs.reduce((s,p)=>s+p[0],0)/n,my=pairs.reduce((s,p)=>s+p[1],0)/n,sxx=pairs.reduce((s,p)=>s+(p[0]-mx)**2,0);if(!sxx)return null;const b=pairs.reduce((s,p)=>s+(p[0]-mx)*(p[1]-my),0)/sxx,a=my-b*mx;const res=pairs.map(p=>p[1]-(a+b*p[0])),sd=Math.sqrt(res.reduce((s,r)=>s+r*r,0)/Math.max(1,n-2));return{a,b,sd};}
function revenueForecast(pairs,x){if(pairs.length<8||x==null)return null;const r=pearson(pairs);const f=linfit(pairs);if(!f)return null;
 const errs=[];for(let i=Math.max(6,pairs.length-4);i<pairs.length;i++){const g=linfit(pairs.slice(0,i));if(g&&pairs[i][1])errs.push(Math.abs((g.a+g.b*pairs[i][0])/pairs[i][1]-1)*100);}
 const mape=errs.length?errs.reduce((s,e)=>s+e,0)/errs.length:null;const xs=pairs.map(p=>p[0]),lo=Math.min(...xs),hi=Math.max(...xs);const extrap=x<lo*0.7||x>hi*1.3;
 const fail=r==null||r<0.5?'상관계수 0.5 미만 (r='+(r??0).toFixed(2)+')':mape!=null&&mape>30?'백테스트 오차 '+mape.toFixed(0)+'%로 신뢰 낮음':extrap?'추정 수출액이 과거 범위를 크게 벗어나 외삽 위험':null;
 return{value:f.a+f.b*x,low:f.a+f.b*x-f.sd,high:f.a+f.b*x+f.sd,r,n:pairs.length,mape,tests:errs.length,fail};}
function yoyFlag(v){return v!=null&&Math.abs(v)>200?' ⚠ 변동 과다(소규모·단절 가능)':'';}

// 업체 목록용: 기본 보기(사업장 합계 또는 대표 지역)로 진행 분기 추정과 매출 예상을 계산합니다.
function companyOutlook(c){const h=allSitesHS(c)||c.hs_codes.find(x=>queryHS(c,x));if(!h)return{note:'지역 조회 품목 없음'};
 const cr=comboRows(c,h);let sel;
 if(cr.keys.length>1){sel=series(cr.rows);const all=sel.at(-1)?.month;while(sel.length&&sel.at(-1).value==null)sel.pop();}
 else if(cr.keys.length===1){const [sd,rg]=cr.keys[0].split('|'),q=queryHS(c,h);sel=series(regional.filter(r=>r.hs_code===q&&r.sido_code===sd&&r.region===rg).map(r=>{const b=breaks.find(x=>x.hs_code===r.hs_code&&x.region===r.region&&r.month<=x.excluded_through);return{month:r.month,value:b?null:num(r.export_amount_raw)};}));}
 else return{note:'지역 자료 미확보'};
 if(!sel.length)return{note:'지역 자료 미확보'};
 const quarter=quarterly(sel),qv=new Map(quarter.map(q=>[q.period,q.value])),est=estimateQuarter(sel);
 const fin=new Map(financial.filter(r=>r.company_id===c.id).map(r=>[r.period,num(r.revenue_KRW)]));
 const pairs=quarter.filter(q=>q.value!=null&&fin.get(q.period)!=null).map(q=>[q.value,fin.get(q.period)/1e8]);
 const prevQ=p=>`${Number(p.slice(0,4))-1}${p.slice(4)}`;
 const out={est,pairs:pairs.length,r:pairs.length>=3?pearson(pairs):null};
 if(est){out.period=est.period;out.exportYoy=growth(est.total,qv.get(prevQ(est.period)));const fc=revenueForecast(pairs,est.total);if(fc&&!fc.fail){out.fc=fc;const pr=fin.get(prevQ(est.period));out.revYoy=pr?growth(fc.value,pr/1e8):null;}else out.note=pairs.length<8?'완전분기 8개 미만':fc.fail;}
 else{const lastQ=quarter.filter(q=>q.value!=null).at(-1);out.period=lastQ?.period;out.exportYoy=lastQ?growth(lastQ.value,qv.get(prevQ(lastQ.period))):null;out.note='진행 분기 추정 대상 아님(최신 분기 완결 또는 자료 부족)';}
 return out;}
function populateRegions(){const c=watch.find(c=>c.id===el('company').value),h=el('hs').value;el('region').replaceChildren();const rows=regionRows(c,h),seen=new Set();const names=[...new Set(rows.map(r=>r.sido_code+'|'+r.region))];if(names.length>1)option(el('region'),'combo','사업장 합계 · '+names.map(k=>k.split('|')[1].split(' ').at(-1)).join(' + '));for(const r of rows){const key=r.sido_code+'|'+r.region;if(!seen.has(key)){option(el('region'),key,r.region);seen.add(key);}}if(!seen.size)option(el('region'),'missing',queryHS(c,h)?'대상 지역 데이터 미확보':'HS4 지역 조회 미지원');option(el('region'),'national','전국 · 관리 품목 비교용');render();}

function backlogReview(id){return backlogCoverage.companies?.find(r=>r.company_id===id);}
function backlogStatus(id){const review=backlogReview(id),count=backlog.filter(r=>r.company_id===id&&num(r.value)!=null).length;return (count?'금액 '+count+'개 분기 · ':'')+(review?.label||'공시 확인 필요')+(review?.reviewed_period?' · '+review.reviewed_period:'');}
function renderBacklog(c){
 const rows=backlog.filter(r=>r.company_id===c.id&&num(r.value)!=null).sort((a,b)=>a.period.localeCompare(b.period)),review=backlogReview(c.id);
 el('backlogTitle').textContent=c.name+' · 분기 수주잔고';
 el('backlogNote').textContent=(review?.reason||'추가 공시 확인 필요')+(review?.reviewed_period?' · 점검 공시: '+review.reviewed_period:'')+(review?.expected_quarters?' · '+backlogCoverage.start_period+' ~ '+backlogCoverage.end_period+' · '+review.complete_quarters+'/'+review.expected_quarters+'분기 확보':'')+' · 미확인 분기는 0으로 채우지 않습니다. 수주잔고는 기말 잔액으로 분기 매출과 합산하지 않습니다.';
 el('backlogSources').replaceChildren();
 if(review?.source?.startsWith('https://')){const a=document.createElement('a');a.href=review.source;a.textContent='점검 공시 원문';a.target='_blank';a.rel='noopener';el('backlogSources').append(a);}
 el('backlogRows').replaceChildren();
 for(const r of [...rows].reverse()){const tr=document.createElement('tr');[r.period,Number(r.value).toLocaleString(undefined,{maximumFractionDigits:3}),r.unit_label,r.scope||'기존 참고자료 기준',r.notes||r.status].forEach(v=>cell(tr,v));const td=cell(tr,'');if(r.source?.startsWith('https://')){const a=document.createElement('a');a.href=r.source;a.textContent=r.status;a.target='_blank';a.rel='noopener';td.append(a);}el('backlogRows').append(tr);}
 el('backlog').hidden=!rows.length;el('backlogEmpty').hidden=!!rows.length;
 if(!rows.length){if(charts.backlog){charts.backlog.destroy();delete charts.backlog;}el('backlogEmpty').textContent=review?.label||'확인 가능한 수주잔고 금액이 없습니다.';return;}
 const unit=rows[0].unit_label;
 if(rows.some(r=>r.unit!==rows[0].unit||r.scope!==rows[0].scope)){throw Error(c.name+' 수주잔고의 단위 또는 집계 범위가 다릅니다.');}
 const qid=p=>Number(p.slice(0,4))*4+Number(p.at(-1))-1,start=qid(backlogCoverage.start_period||rows[0].period),end=qid(backlogCoverage.end_period||rows.at(-1).period),periods=Array.from({length:end-start+1},(_,i)=>Math.floor((start+i)/4)+'-Q'+((start+i)%4+1)),map=new Map(rows.map(r=>[r.period,r]));
 el('backlogTitle').textContent=c.name+' · 분기 수주잔고 ('+unit+')';
 chart('backlog',periods,[{type:'bar',label:(rows[0].scope||'수주잔고')+' · '+unit,data:periods.map(p=>num(map.get(p)?.value)),backgroundColor:periods.map(p=>map.get(p)?.status==='공시 확인'?'#087f74':'#94bdb7'),borderColor:'#087f74',borderWidth:1,maxBarThickness:44}],'수주잔고 ('+unit+')',{scales:{y:{beginAtZero:true,title:{display:true,text:'수주잔고 ('+unit+')'},ticks:{callback:v=>Number(v).toLocaleString()}}},plugins:{tooltip:{callbacks:{label:ctx=>'수주잔고: '+Number(ctx.parsed.y).toLocaleString()+' '+unit,afterLabel:ctx=>{const r=map.get(periods[ctx.dataIndex]);return [r?.status||'',r?.notes||''];}}}}});
}

function render(){const c=watch.find(c=>c.id===el('company').value),hs=el('hs').value,reg=el('region').value,isNational=reg==='national',query=queryHS(c,hs);let [sido,regionName]=reg.split('|');
 const national=series(nationwide.filter(r=>r['HS코드']===natHS(c,hs)).map(r=>({month:r['월'],value:num(r['수출금액_USD'])})));
 const isCombo=reg==='combo';let breakNote='';
 const cut=rows=>rows.map(r=>{const b=breaks.find(x=>x.hs_code===r.hs_code&&x.region===r.region&&r.month<=x.excluded_through);if(b&&!isCombo){breakNote=b.region+' '+b.excluded_through+' 이전 제외: '+b.reason;return{...r,value:null};}return r;});
 let selected;
 if(isNational)selected=national;
 else if(isCombo){const cr=comboRows(c,hs),keys=cr.keys;selected=series(cr.rows);const allLast=selected.at(-1)?.month;while(selected.length&&selected.at(-1).value==null)selected.pop();if(selected.length&&selected.at(-1).month!==allLast)breakNote='일부 사업장의 '+allLast+'까지 자료가 아직 없어 합계는 '+selected.at(-1).month+'까지 표시합니다. 지역별 최신 값은 지역 선택에서 확인하세요.';regionName=keys.map(k=>k.split('|')[1]).join(' + ');sido=keys[0].split('|')[0];}
 else selected=series(cut(regional.filter(r=>r.hs_code===query&&r.sido_code===sido&&r.region===regionName).map(r=>({month:r.month,hs_code:r.hs_code,region:r.region,value:num(r.export_amount_raw)}))));
 const quarter=quarterly(selected),qm=new Map(quarter.map(r=>[r.period,r]));
 const est=isNational?null:estimateQuarter(selected);
 const fin=financial.filter(r=>r.company_id===c.id).sort((a,b)=>a.period.localeCompare(b)),fm=new Map(fin.map(r=>[r.period,r]));
 const dfin=domesticFinancial.filter(r=>r.company_id===c.id).sort((a,b)=>a.period.localeCompare(b)),dfm=new Map(dfin.map(r=>[r.period,r]));
 const prior=p=>`${Number(p.slice(0,4))-1}${p.slice(4)}`;
 const fy=p=>growth(num(fm.get(p)?.revenue_KRW),num(fm.get(prior(p))?.revenue_KRW));
 const qy=p=>growth(qm.get(p)?.value,qm.get(prior(p))?.value);
 el('scopeNotice').textContent=isNational?'전국 비교: 관리 품목 '+hs+' 데이터입니다. 지역 상위품목 지표와 범위가 다를 수 있습니다.':!query?'HS 4자리 총괄은 이 지역 API에서 조회할 수 없습니다. 관련 세부 관리 품목을 선택하세요.':query!==hs?'관리 HS '+hs+' → 지역 조회 HS '+query+' 상위 품목군 참고지표. 세부 품목 전용 수출이 아닙니다.':'지역 조회 HS '+query+' · 해당 지역 품목군 전체. 개별 업체 수출액이 아닙니다.';
 if(isCombo)el('scopeNotice').textContent='사업장 합계: '+regionName+'의 HS '+query+' 지역 수출을 월별로 더한 값입니다. 모든 사업장 값이 있는 달만 계산합니다. 각 지역에는 다른 업체 수출도 포함됩니다.';
 if(breakNote)el('scopeNotice').textContent+=isCombo?' ⚠ '+breakNote:' ⚠ 시계열 단절 구간 제외 — '+breakNote;
 const peers=watch.filter(x=>x.id!==c.id&&x.hs_codes.some(h=>queryHS(x,h)===query&&sites(x,h).some(t=>t.sido_code===sido&&regionName?.includes(t.region_keyword))));el('sharedCandidates').textContent=isNational?'':peers.length?'동일 지역·HS 통계를 공유하는 후보: '+peers.map(x=>x.name).join(', ')+' — 업체별 기여도 분리 불가.':'목록 내 동일 지역·HS 후보가 없더라도 해당 업체의 독점 수출을 뜻하지 않습니다.';
 el('mapping').textContent=`${c.name} (${c.id}) · ${c.region_basis}. ${c.rationale}`;
 el('coverage').textContent=`선택 지역: ${isNational?'전국':reg==='missing'?sites(c,hs).map(t=>t.region_keyword).join(' · '):regionName} | 확보 ${selected.filter(r=>r.value!=null).length}개월 | 수집 확인: ${status.updated_at??'아직 실행 결과 없음'}${status.failures?.length?' | 수집 실패 '+status.failures.length+'구간 · 기존 정상 데이터 유지':''}`;
 const i=selected.length-1,last=selected[i],map=new Map(selected.map(r=>[r.month,r.value]));
 el('yoy').textContent=pct(last?growth(last.value,map.get(monthLabel(monthId(last.month)-12))):null);el('latest').textContent=last?last.month+' · '+(isNational?'전국':regionName):'지역 데이터 미확보';
 el('maYoy').textContent=pct(growth(average(selected,i),average(selected,i-12)));
 const latestFin=[...fin].reverse().find(r=>fy(r.period)!=null)||fin.at(-1);el('revenueYoy').textContent=latestFin?pct(fy(latestFin.period)):'—';el('revenueLatest').textContent=latestFin?(fy(latestFin.period)!=null?latestFin.period+' · '+latestFin.status:latestFin.period+' · 전년동기 공시 미확보'):'공시 미확보';
 const pairs=quarter.map(q=>[qy(q.period),fy(q.period)]).filter(p=>p.every(v=>v!=null));
 const agree=pairs.length?pairs.filter(p=>Math.sign(p[0])===Math.sign(p[1])).length/pairs.length*100:null;
 const confidence=pairs.length>=8?'참고 가능':pairs.length>=3?'초기 신호':'표본 부족';
 el('agreement').textContent=agree==null?'표본 부족':`${agree.toFixed(0)}% · ${confidence}`;
 el('pairs').textContent=`동일 분기 YoY ${pairs.length}쌍 · 3쌍부터 초기 신호, 8쌍부터 참고 가능`;
 el('validation').textContent=pairs.length<3?`${pairs.length}개 비교 분기 확보. 방향 일치율을 표시하기에는 표본이 부족합니다.`:pairs.length<8?`${pairs.length}개 비교 분기의 초기 신호입니다. 방향 일치율은 참고용으로만 표시하며 매출 예측에는 사용하지 않습니다.`:`${pairs.length}개 비교 분기의 과거 동행성 지표입니다. 표본 외 예측 검증 전에는 매출 전망을 산출하지 않습니다.`;
 const base=selected.find(r=>r.value>0)?.value;const scale=v=>v==null||!base?null:v/base*100;
 el('trendTitle').textContent=(isNational?'전국':reg==='missing'?sites(c,hs).map(t=>t.region_keyword).join(' · '):regionName)+' · '+(isNational?hs:query||hs)+' 수출 추세';
 el('trendEmpty').hidden=!!selected.length;el('trendEmpty').textContent='지역 데이터가 아직 확보되지 않았습니다. 수집 상태를 확인하거나 지역 선택에서 전국 비교를 볼 수 있습니다.';
 if(el('frequency').value==='month'){
 el('trendNote').textContent='첫 유효월=100. 월별 변동은 연속 3개월 이동평균으로 함께 확인합니다. 통화 단위의 배율 확인 전에는 지역 절대금액을 표시하지 않습니다.';
 chart('trend',selected.map(r=>r.month),[{type:'bar',label:'월별 수출 지수',data:selected.map(r=>scale(r.value)),backgroundColor:'#adc8ef'},{label:'3개월 이동평균',data:selected.map((_,i)=>scale(average(selected,i))),borderColor:'#2159a6',borderWidth:3,pointRadius:0}],'수출 지수');
 }else{const qbase=quarter.find(q=>q.value>0)?.value,sc=v=>v==null||!qbase?null:v/qbase*100;const actual=[],estimate=[];quarter.forEach((q,i)=>{const firstMonth=(Number(q.period.at(-1))-1)*3+1;const valid=q.rows.filter(r=>r.value!=null);const can=q.period===quarterly(national).at(-1)?.period&&i===quarter.length-1&&q.months>0&&q.months<3&&valid.every((r,j)=>Number(r.month.slice(5))===firstMonth+j);actual.push(q.months===3||can?sc(q.actual):null);estimate.push(can?sc(est&&est.period===q.period?est.total-est.actual:q.actual/q.months*(3-q.months)):null);});
 el('trendNote').textContent='첫 완전분기=100. 진한색은 확보분, 옅은색은 미확보 월 추정분입니다(확보월의 전년 대비 증감률을 전년 같은 달에 적용, 전년 자료가 없으면 확보월 평균).';
 chart('trend',quarter.map(q=>q.period),[{type:'bar',label:'확보 수출',data:actual,backgroundColor:'#245bb0',stack:'sum'},{type:'bar',label:'미확보 월 추정',data:estimate,backgroundColor:'#c7d9f4',stack:'sum'}],'분기 수출 지수');charts.trend.options.scales.x.stacked=true;charts.trend.options.scales.y.stacked=true;charts.trend.update();}
 const periods=[...new Set([...quarter.map(q=>q.period),...fin.map(f=>f.period)])].sort();
 const monthlyMap=new Map(selected.map(r=>[r.month,r.value]));
 const monthlyYoy=p=>growth(monthlyMap.get(p),monthlyMap.get(monthLabel(monthId(p)-12)));
 const monthlyMode=el('frequency').value==='month';
 const comparisonPeriods=monthlyMode?selected.map(r=>r.month):periods;
 chart('comparison',comparisonPeriods,[{label:monthlyMode?'수출 YoY · 월별':'수출 YoY · 완전분기',data:comparisonPeriods.map(monthlyMode?monthlyYoy:qy),borderColor:'#2784b8',pointRadius:3},...(monthlyMode?[{label:'수출 YoY · 월평균(3개월)',data:selected.map((_,i)=>growth(average(selected,i),average(selected,i-12))),borderColor:'#7c3aed',borderDash:[6,4],pointRadius:0,borderWidth:2}]:[]),{label:monthlyMode?'공시 매출 YoY · 분기 자료':'매출 YoY',data:comparisonPeriods.map(monthlyMode?()=>null:fy),borderColor:'#27925c',pointRadius:5,borderWidth:3,spanGaps:true}],'전년 동기 대비 (%)');
 if(el('comparisonNote'))el('comparisonNote').textContent=monthlyMode?'월별 선택: 수출 YoY는 동일 월 전년 대비(실선), 월평균 YoY는 최근 3개월 월평균 ÷ 전년 같은 3개월 월평균(점선)입니다. 공시 매출은 분기 자료만 있어 월별 그래프에는 표시하지 않습니다.':'분기별 선택: 수출 YoY와 회사 공시 매출 YoY를 동일 분기 기준으로 비교합니다.';
 const amountPeriods=monthlyMode?selected.map(r=>r.month):quarter.map(q=>q.period);
 const exportAmounts=monthlyMode?selected.map(r=>r.value):quarter.map(q=>q.value);
 const qMap=new Map(quarter.map(q=>[q.period,q.value]));
 const qExport=monthlyMode?amountPeriods.map(p=>Number(p.slice(5))%3===0?(qMap.get(`${p.slice(0,4)}-Q${Number(p.slice(5))/3}`)??null):null):exportAmounts;
 const estMap=new Map((est?.est||[]).map(r=>[r.month,r.value]));
 if(monthlyMode&&est&&!amountPeriods.includes(est.endMonth)){est.est.forEach(r=>{if(!amountPeriods.includes(r.month))amountPeriods.push(r.month);});}
 const estMonthly=monthlyMode&&est?amountPeriods.map(p=>estMap.has(p)?estMap.get(p):(p===est.have.at(-1)?selected.find(r=>r.month===p)?.value??null:null)):null;
 const estQuarter=monthlyMode&&est?amountPeriods.map(p=>p===est.endMonth?est.total:null):null;
 const exportSets=monthlyMode?[{label:'지역 수출액 · 분기 합계 (USD)',data:qExport,borderColor:'#2784b8',backgroundColor:'#2784b8',pointRadius:4,borderWidth:3,spanGaps:true,yAxisID:'yExport'},{label:'지역 수출액 · 월별 (USD, 점선)',data:exportAmounts,borderColor:'#2784b8',borderDash:[4,4],borderWidth:1.5,pointRadius:0,spanGaps:false,yAxisID:'yExport'},...(est?[{label:'추정 · 미수집 월 ('+(est.method==='yoy'?'확보월 YoY 적용':'확보월 평균')+')',data:estMonthly,borderColor:'#9bbad3',borderDash:[2,3],borderWidth:1.5,pointRadius:4,pointStyle:'rectRot',pointBackgroundColor:'#ffffff',spanGaps:true,yAxisID:'yExport'},{label:'추정 · '+est.period+' 분기 합계',data:estQuarter,borderColor:'#2784b8',pointRadius:7,pointBackgroundColor:'#ffffff',pointBorderWidth:2,showLine:false,yAxisID:'yExport'}]:[])]:[{label:'지역 수출액 · USD',data:exportAmounts,borderColor:'#2784b8',pointRadius:2,yAxisID:'yExport'}];
 const revenueAmounts=monthlyMode?amountPeriods.map(p=>{const q=`${p.slice(0,4)}-Q${Math.ceil(Number(p.slice(5))/3)}`;const v=num(fm.get(q)?.revenue_KRW);return Number(p.slice(5))%3===0&&v!=null?v/1e8:null;}):amountPeriods.map(p=>{const v=num(fm.get(p)?.revenue_KRW);return v==null?null:v/1e8;});
 chart('amountComparison',amountPeriods,[...exportSets,{label:c.name+' 매출액 · 억원',data:revenueAmounts,borderColor:'#d97835',pointRadius:4,borderWidth:3,spanGaps:true,yAxisID:'yRevenue'}],'금액',{spanGaps:true,scales:{y:{display:false},yExport:{type:'linear',position:'left',title:{display:true,text:'수출액 (USD · 신고미화금액)'},ticks:{callback:v=>Number(v).toLocaleString()}},yRevenue:{type:'linear',position:'right',title:{display:true,text:'회사 매출액 (억원)'},grid:{drawOnChartArea:false},ticks:{callback:v=>Number(v).toLocaleString()}}},plugins:{tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${Number(ctx.parsed.y).toLocaleString()} ${ctx.dataset.yAxisID==='yRevenue'?'억원':'USD'}`}}}});
 const revenueCorrPairs=amountPeriods.map((p,i)=>[qExport[i],revenueAmounts[i]]).filter(([x,y])=>x!=null&&y!=null);if(el('amountCorrelationNote'))el('amountCorrelationNote').textContent=corrText(pearson(revenueCorrPairs),revenueCorrPairs.length);
 {const ch=charts.amountComparison;let fNote='';
  if(est&&!monthlyMode){if(!ch.data.labels.includes(est.period))ch.data.labels.push(est.period);const k=ch.data.labels.indexOf(est.period);const d=ch.data.labels.map((_,i)=>i===k?est.total:null);ch.data.datasets.splice(1,0,{label:'추정 · '+est.period+' 분기 합계',data:d,borderColor:'#2784b8',pointRadius:7,pointBackgroundColor:'#ffffff',pointBorderWidth:2,showLine:false,yAxisID:'yExport'});}
  const fc=est?revenueForecast(revenueCorrPairs,est.total):null;
  if(fc&&!fc.fail){const pos=monthlyMode?est.endMonth:est.period;if(!ch.data.labels.includes(pos))ch.data.labels.push(pos);const k=ch.data.labels.indexOf(pos);
   ch.data.datasets.push({label:'예상 · '+est.period+' 매출 (회귀)',data:ch.data.labels.map((_,i)=>i===k?fc.value:null),borderColor:'#d97835',pointRadius:8,pointStyle:'triangle',pointBackgroundColor:'#ffffff',pointBorderWidth:2,showLine:false,yAxisID:'yRevenue'});ch.update();
   fNote=` · ${est.period} 매출 예상 ${Math.round(fc.value).toLocaleString()}억원 (±1σ ${Math.round(fc.low).toLocaleString()}~${Math.round(fc.high).toLocaleString()}억원, 회귀 r=${fc.r.toFixed(2)}, 완전분기 ${fc.n}개${fc.mape!=null?`, 최근 ${fc.tests}개 분기 순차 백테스트 평균 오차 ${fc.mape.toFixed(1)}%`:''})`;}
  else if(est)fNote=` · 매출 예상 미표시: ${fc?fc.fail:'완전분기 8개 미만 또는 자료 부족'}`;
  if(est)fNote=` · ${est.period} 수출 추정: 확보 ${est.have.join('·')} 합계 ${Math.round(est.actual).toLocaleString()}${est.method==='yoy'?` → 확보월 전년 대비 ${((est.ratio-1)*100).toFixed(1)}%를 미수집 월(${est.est.map(r=>r.month).join('·')}) 전년 값에 적용`:' → 전년 자료가 없어 확보월 평균 적용'}, 분기 합계 추정 ${Math.round(est.total).toLocaleString()} (흰 점 = 추정분)`+fNote;
  el('amountForecastNote')&&(el('amountForecastNote').textContent=fNote?('추정·예상'+fNote+'. 지역 통계에는 다른 업체 수출이 포함되며, 예상치는 과거 관계가 유지된다는 가정의 참고값입니다.'):'');}
 correlationChart('connectedCorrelation',revenueCorrPairs,'수출액 (USD)','연결매출 (억원)');
 if(el('amountNote'))el('amountNote').textContent=monthlyMode?'굵은 선은 분기 합계 수출액(3개월 모두 확보된 분기, 분기 말월에 표시), 점선은 월별 수출액입니다. 좌측 수출액은 관세청 API 신고미화금액(USD), 우측 매출액은 공시 원화 매출을 억원으로 환산했습니다. 매출선은 확보된 공시 시점을 연결하며 누락 구간은 추정하지 않습니다.':'좌측 수출액은 관세청 API 신고미화금액(USD), 우측 매출액은 공시 원화 매출을 억원으로 환산했습니다. 매출선은 확보된 공시 시점을 연결하며 누락 구간은 추정하지 않습니다.';
 const domesticAmounts=monthlyMode?amountPeriods.map(p=>{const q=`${p.slice(0,4)}-Q${Math.ceil(Number(p.slice(5))/3)}`;const v=num(dfm.get(q)?.domestic_revenue_KRW);return Number(p.slice(5))%3===0&&v!=null?v/1e8:null;}):amountPeriods.map(p=>{const v=num(dfm.get(p)?.domestic_revenue_KRW);return v==null?null:v/1e8;});
 chart('domesticComparison',amountPeriods,[...exportSets,{label:c.name+' 국내법인 별도 매출 · 억원',data:domesticAmounts,borderColor:'#008b87',pointRadius:4,borderWidth:3,spanGaps:true,yAxisID:'yRevenue'}],'금액',{spanGaps:true,scales:{y:{display:false},yExport:{type:'linear',position:'left',title:{display:true,text:'수출액 (USD · 신고미화금액)'},ticks:{callback:v=>Number(v).toLocaleString()}},yRevenue:{type:'linear',position:'right',title:{display:true,text:'국내법인 별도 매출 (억원)'},grid:{drawOnChartArea:false},ticks:{callback:v=>Number(v).toLocaleString()}}},plugins:{tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${Number(ctx.parsed.y).toLocaleString()} ${ctx.dataset.yAxisID==='yRevenue'?'억원':'USD'}`}}}});
 const domesticCorrPairs=amountPeriods.map((p,i)=>[qExport[i],domesticAmounts[i]]).filter(([x,y])=>x!=null&&y!=null);if(el('domesticCorrelationNote'))el('domesticCorrelationNote').textContent=corrText(pearson(domesticCorrPairs),domesticCorrPairs.length);
 correlationChart('standaloneCorrelation',domesticCorrPairs,'수출액 (USD)','별도매출 (억원)');
 if(el('domesticAmountNote'))el('domesticAmountNote').textContent=domesticAmounts.some(v=>v!=null)?'국내법인 별도재무제표 기준 매출. 2020년 이후 확인된 분기 공시값을 표시하며, 설립 전·미확인 분기는 공란으로 유지합니다. 연결매출과 혼용하지 않습니다.':'국내법인 별도재무제표 기준. 확인된 별도 공시값이 없어 선은 공란으로 유지됩니다. 연결매출과 혼용하지 않습니다.';
 const nrows=nationwide.filter(r=>r['HS코드']===natHS(c,hs)).sort((a,b)=>a['월'].localeCompare(b['월']));
 chart('price',nrows.map(r=>r['월']),[{label:'전국 USD/KG',data:nrows.map(r=>{const w=num(r['수출중량_KG']),v=num(r['수출금액_USD']);return w>0&&v!=null?v/w:null;}),borderColor:'#b47737',pointRadius:0}],'USD/KG');
 const earningsPeriods=[];const qi=p=>Number(p.slice(0,4))*4+Number(p.at(-1))-1;
 const rangeStart=financialCoverage.start_period||fin[0]?.period,rangeEnd=financialCoverage.end_period||fin.at(-1)?.period;
 if(rangeStart&&rangeEnd)for(let q=qi(rangeStart);q<=qi(rangeEnd);q++)earningsPeriods.push(Math.floor(q/4)+'-Q'+(q%4+1));
 const notApplicable=financialCoverage.companies?.find(r=>r.company_id===c.id)?.not_applicable_periods||[];
 const earningsMissing=earningsPeriods.filter(p=>!notApplicable.includes(p)).filter(p=>num(fm.get(p)?.revenue_KRW)==null||opm(fm.get(p))==null);
 el('earningsTitle').textContent=c.name+' · 분기 매출·OPM';
 el('earningsNote').textContent=(rangeStart?rangeStart+' ~ '+rangeEnd+' · ':'')+'연결 분기 실적 · '+(earningsPeriods.length-notApplicable.length-earningsMissing.length)+'/'+(earningsPeriods.length-notApplicable.length)+'분기 확보 · '+(earningsMissing.length?'미확보: '+earningsMissing.join(', '):'누락 없음')+(notApplicable.length?' · 공시 회계기간 시작 전: '+notApplicable.join(', '):'')+'. OPM = 영업이익 ÷ 매출 × 100. 4분기는 연간−3분기 누적으로 산출하며 아래 표에 두 공시 원문을 표시합니다.';
 chart('revenue',earningsPeriods,[{type:'bar',label:'매출액 (좌 · 억원)',data:earningsPeriods.map(p=>{const v=num(fm.get(p)?.revenue_KRW);return v==null?null:v/1e8;}),backgroundColor:'#b7bdc4',yAxisID:'y',order:1,maxBarThickness:46},{type:'line',label:'OPM (우 · %)',data:earningsPeriods.map(p=>opm(fm.get(p))),borderColor:'#008b87',backgroundColor:'#008b87',borderWidth:3,pointRadius:4,yAxisID:'yOPM',order:0,spanGaps:false}],'매출액 (억원)',{scales:{y:{type:'linear',position:'left',beginAtZero:true,title:{display:true,text:'매출액 (억원)'}},yOPM:{type:'linear',position:'right',title:{display:true,text:'OPM (%)'},grid:{drawOnChartArea:false},ticks:{callback:v=>v+'%'}}},plugins:{tooltip:{callbacks:{label:ctx=>ctx.dataset.yAxisID==='yOPM'?'OPM: '+ctx.parsed.y.toFixed(2)+'%':'매출액: '+ctx.parsed.y.toLocaleString(undefined,{maximumFractionDigits:1})+'억원'}}}});
 renderBacklog(c);

 tableRows=periods.map(p=>({period:p,months:qm.get(p)?.months??0,export_yoy:qy(p),revenue_KRW:num(fm.get(p)?.revenue_KRW),revenue_yoy:fy(p),operating_profit_KRW:num(fm.get(p)?.operating_profit_KRW),opm_pct:opm(fm.get(p)),source:fm.get(p)?.source??'',source_secondary:fm.get(p)?.source_secondary??'',status:fm.get(p)?.status??''}));
 el('rows').replaceChildren();[...tableRows].reverse().forEach(r=>{const tr=document.createElement('tr');[r.period,r.months+'/3',pct(r.export_yoy),r.revenue_KRW==null?'—':(r.revenue_KRW/1e8).toLocaleString(undefined,{maximumFractionDigits:1}),pct(r.revenue_yoy),r.operating_profit_KRW==null?'—':(r.operating_profit_KRW/1e8).toLocaleString(undefined,{maximumFractionDigits:1}),pct(r.opm_pct)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td);});const td=document.createElement('td');if(r.source.startsWith('https://')){const a=document.createElement('a');a.href=r.source;a.textContent=r.status;a.target='_blank';a.rel='noopener';td.append(a);}if(r.source_secondary?.startsWith('https://')){const a=document.createElement('a');a.href=r.source_secondary;a.textContent=' · 3분기 누적 원문';a.target='_blank';a.rel='noopener';td.append(a);}tr.append(td);el('rows').append(tr);});
 el('sources').replaceChildren();c.sources.forEach((url,i)=>{const a=document.createElement('a');a.href=url;a.textContent=`선정 근거 ${i+1} `;a.target='_blank';a.rel='noopener';el('sources').append(a);});
}
el('download').onclick=()=>{const h=['period','months','export_yoy','revenue_KRW','revenue_yoy','operating_profit_KRW','opm_pct','source','source_secondary','status'];const data='\uFEFF'+[['company_id','managed_hs','query_hs','region',...h].join(','),...tableRows.map(r=>[el('company').value,el('hs').value,queryHS(watch.find(c=>c.id===el('company').value),el('hs').value)||'',el('region').value,...h.map(k=>r[k]??'')].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`company-${el('company').value}-${el('hs').value}-comparison.csv`;a.click();URL.revokeObjectURL(url);};
function cell(tr,text){const td=document.createElement('td');td.textContent=text;tr.append(td);return td;}
function choose(c,h){el('category').value=c.category;populateCompany();el('company').value=c.id;populateHS();if(h){el('hs').value=h;populateRegions();}el('company').scrollIntoView({behavior:'smooth',block:'center'});}
function companyButton(c,h){const b=document.createElement('button');b.textContent=c.name;b.onclick=()=>choose(c,h);return b;}
function renderUniverse(){if(!el('companyList'))return;const term=(el('companySearch')?.value||'').trim().toLowerCase(),cat=el('industryFilter')?.value||'';el('companyList').replaceChildren();const filtered=watch.filter(c=>(!cat||c.category===cat)&&[c.name,c.id,c.category,...sites(c).map(s=>s.region_keyword),...c.hs_codes,...c.hs_codes.map(h=>hsNames[h])].join(' ').toLowerCase().includes(term));for(const c of filtered){const tr=document.createElement('tr');cell(tr,c.category);const name=cell(tr,'');name.append(companyButton(c));const id=document.createElement('small');id.textContent=c.id==='LS-CABLE'?'비상장 제조사':c.id;name.append(id);cell(tr,[...new Set(sites(c).map(s=>s.region_keyword))].join(' · '));cell(tr,c.hs_codes.map(h=>hsNames[h]+' ('+h+')').join(' / '));const logical=allSitesHS(c)||c.hs_codes.find(h=>queryHS(c,h)),q=logical?queryHS(c,logical):null;const site=logical?sites(c,logical)[0]:null;const rs=site?regionRows(c,logical).filter(r=>r.sido_code===site.sido_code&&r.region.includes(site.region_keyword)).sort((a,b)=>a.month.localeCompare(b.month)):[];const regions=[...new Set(rs.map(r=>r.region))];const last=regions.length===1?rs.at(-1):null,prev=last?rs.find(r=>r.month===monthLabel(monthId(last.month)-12)):null;const combo=logical?comboRows(c,logical):null;if(combo&&combo.keys.length>1){const cr=combo.rows.filter(r=>r.value!=null),cl=cr.at(-1),cp=cl?combo.rows.find(r=>r.month===monthLabel(monthId(cl.month)-12)):null;cell(tr,cl?pct(growth(cl.value,cp?.value))+' · '+cl.month+' · 사업장 합계('+combo.keys.map(k=>k.split('|')[1].split(' ').at(-1)).join('+')+') · HS'+q:'사업장 합계 미확보');}else cell(tr,last?pct(growth(num(last.export_amount_raw),num(prev?.export_amount_raw)))+' · '+last.month+' · '+last.region+' · HS'+q:'미확보 / 대표지역 단일 시계열 확인 필요');const count=new Set(c.hs_codes.flatMap(h=>regionRows(c,h).map(r=>[r.month,r.hs_code,r.sido_code,r.region].join('|')))).size;cell(tr,(c.hs_codes.some(h=>h.length===10)?'HS6 상위 품목군 포함':'HS6 품목군')+' · '+count+'행');const coverage=financialCoverage.companies?.find(r=>r.company_id===c.id);cell(tr,coverage?coverage.complete_quarters+'/'+coverage.expected_quarters+'분기 · '+(coverage.status==='complete'?'누락 없음':coverage.status==='not_collected'?'실적 미확보':'누락 '+coverage.missing_periods.join(', ')):'실적 범위 미확인');cell(tr,backlogStatus(c.id));{const o=companyOutlook(c);cell(tr,o.period?(o.est?o.period+' 추정 ':o.period+' 확정 ')+pct(o.exportYoy)+yoyFlag(o.exportYoy):(o.note||'—'));cell(tr,o.fc?Math.round(o.fc.value).toLocaleString()+'억원 '+(o.revYoy!=null?'(전년비 '+pct(o.revYoy)+')':'')+' · 오차 '+(o.fc.mape!=null?o.fc.mape.toFixed(0)+'%':'—'):(o.note||'—'));}const td=cell(tr,'');const link=document.createElement('a');link.href=c.sources[0];link.textContent='공식 근거';link.target='_blank';link.rel='noopener';td.append(link);el('companyList').append(tr);}if(el('listCount'))el('listCount').textContent=filtered.length+' / '+watch.length+'개 업체 표시 · YoY는 표에 적힌 지역·품목군 값이며, 사업장이 여러 지역이면 사업장 합계입니다.';}
function renderCoverage(){if(!el('hsCoverage'))return;el('hsCoverage').replaceChildren();for(const [h,name] of Object.entries(hsNames)){const tr=document.createElement('tr');cell(tr,name+' · '+h);const cs=watch.filter(c=>c.hs_codes.includes(h));cell(tr,h.length===4?'직접 조회 미지원':h.slice(0,6)+(h.length===10?' · 상위 품목군':''));const td=cell(tr,'');cs.forEach(c=>{td.append(companyButton(c,h),document.createTextNode(' '));});if(!cs.length)td.textContent='확인된 연결 없음';cell(tr,watchMeta.unmapped_notes?.[h]||(h.length===4?'총괄을 임의의 세부 코드로 대체하지 않습니다.':h.startsWith('300249')||h.startsWith('854143')?'2022년 이전 지역 시계열 미연결. 월간 대시보드의 과거 HS 연결은 유지.':h.length===10?'제품·생산지역 근거로 연결한 후보. 개별 수출 신고코드·점유율 미확인.':'제품·생산지역 근거로 연결한 후보. 지역 통계에는 타 업체가 포함됩니다.'));el('hsCoverage').append(tr);}}
async function init(){try{const bt=await read('regional_breaks.json',true);breaks=bt?JSON.parse(bt).breaks||[]:[];}catch(e){breaks=[];}const [w,h,n,r,s,f,fc,b,bc]=await Promise.all([read('company_watchlist.json'),read('hs_codes.csv'),read('summary_all.csv'),read('regional_exports.csv',true),read('regional_status.json',true),read('company_financials.csv'),read('company_financial_coverage.json',true),read('company_backlog.csv',true),read('company_backlog_coverage.json',true)]);watchMeta=JSON.parse(w);watch=watchMeta.companies;hsNames=Object.fromEntries(csv(h).slice(1).map(r=>[r[0],r.slice(1).join(',')]));if(watch.some(c=>c.hs_codes.some(h=>!hsNames[h])))throw Error('관심업체 HS코드가 hs_codes.csv에 없습니다.');nationwide=records(n);regional=r?records(r):[];status=s?JSON.parse(s):{};financial=records(f);financialCoverage=fc?JSON.parse(fc):{};backlog=b?records(b):[];backlogCoverage=bc?JSON.parse(bc):{};if(el('financialCoverageSummary')){const cs=financialCoverage.companies||[];el('financialCoverageSummary').textContent=cs.length?'실적 점검 범위 '+financialCoverage.start_period+' ~ '+financialCoverage.end_period+' · 연속 분기 확보 '+cs.filter(c=>c.status==='complete').length+'/'+cs.length+'개 업체. 나머지 업체의 미확보 상태는 아래 목록에 표시합니다. 확인일 '+financialCoverage.reviewed_at:'실적 수집 범위 확인 필요';}el('accessNotice').hidden=!status.failures?.some(f=>/SERVICE_KEY|ACCESS_DENIED|PERMISSION|HTTP_401|HTTP_403/.test(f.error));const categories=[...new Set(watch.map(c=>c.category))];categories.forEach(c=>{option(el('category'),c,c);if(el('industryFilter'))option(el('industryFilter'),c,c);});if(el('universeSummary')){const backlogCompanies=new Set(backlog.filter(r=>num(r.value)!=null).map(r=>r.company_id));el('universeSummary').textContent=watch.length+'개 업체 · '+watch.flatMap(c=>sites(c)).length+'개 업체-생산지역 연결 · '+new Set(watch.flatMap(c=>c.hs_codes)).size+'/'+Object.keys(hsNames).length+'개 관리 품목에 후보 연결 · 수주잔고 확인 '+backlogCompanies.size+'/'+watch.length+'개 업체 · 비공개·미기재 등 '+(watch.length-backlogCompanies.size)+'개 업체. 업체별 점검 공시 기간이 다르며 모든 과거 분기를 확보한 것은 아닙니다.';}if(el('reviewDate'))el('reviewDate').textContent=watchMeta.reviewed_at||'2026-10-07';if(el('companySearch'))el('companySearch').oninput=renderUniverse;if(el('industryFilter'))el('industryFilter').onchange=renderUniverse;renderUniverse();renderCoverage();el('category').onchange=populateCompany;el('company').onchange=populateHS;el('hs').onchange=populateRegions;el('region').onchange=render;el('frequency').onchange=render;populateCompany();}
fetch('company_domestic_financials.csv?v='+Date.now()).then(r=>r.ok?r.text():'').then(t=>{if(t){domesticFinancial=records(t);if(el('company')?.value)render();}}).catch(()=>{});
init().catch(e=>{el('error').hidden=false;el('error').textContent='데이터를 불러오지 못했습니다: '+e.message;});

