const fs=require('fs'),vm=require('vm'),assert=require('assert');
const dir=__dirname+'/';
class E{constructor(tag='div'){this.tag=tag;this.children=[];this.value='';this.textContent='';this.hidden=false;}append(...cs){const wasEmpty=this.children.length===0;this.children.push(...cs);if(this.tag==='select'&&wasEmpty&&cs.length)this.value=cs[0].value;}replaceChildren(...cs){this.children=[];this.value='';this.append(...cs);}scrollIntoView(){} click(){}}
const html=fs.readFileSync(dir+'regional.html','utf8'),els={};for(const m of html.matchAll(/<(\w+)[^>]*id="([^"]+)"/g))els[m[2]]=new E(m[1]);els.frequency.value='month';els.industryFilter.children.push({value:''});
const files={};for(const f of ['company_watchlist.json','hs_codes.csv','summary_all.csv','company_financials.csv','company_financial_coverage.json','company_backlog.csv','company_backlog_coverage.json'])files[f]=fs.readFileSync(dir+f,'utf8');
// Synthetic test rows only; never saved to the dashboard data.
files['regional_exports.csv']='month,hs_code,sido_code,region,export_amount_raw\n2025.01,853400,41,경기도 안산시,100\n2026.01,853400,41,경기도 안산시,120\n2026.02,853400,41,경기도 안산시,130\n2026.03,853400,41,경기도 안산시,140\n2026.01,854232,41,경기도 평택시,200\n';
files['regional_status.json']='{}';
const ctx={document:{getElementById:id=>els[id]||null,createElement:t=>new E(t),createTextNode:t=>({textContent:t})},fetch:async p=>({ok:true,text:async()=>files[p.split('?')[0]]}),Chart:class{constructor(e,c){this.options=c.options;this.data=c.data;}destroy(){}update(){}},URL:{createObjectURL(){return 'blob:test'},revokeObjectURL(){}},Blob:class{},console};
vm.createContext(ctx);vm.runInContext(fs.readFileSync(dir+'regional.js','utf8'),ctx);
setImmediate(()=>{try{assert(!els.error.textContent,els.error.textContent);assert.equal(els.companyList.children.length,JSON.parse(files['company_watchlist.json']).companies.length);assert.equal(els.hsCoverage.children.length,files['hs_codes.csv'].trim().split('\n').length-1);vm.runInContext(`for(const c of watch){el('category').value=c.category;populateCompany();el('company').value=c.id;populateHS();for(const h of c.hs_codes){el('hs').value=h;populateRegions();el('frequency').value='quarter';render();el('frequency').value='month';render();}}`,ctx);vm.runInContext(`choose(watch.find(c=>c.id==='353200'),'853400')`,ctx);assert(els.sharedCandidates.textContent.includes('코리아써키트'));assert(els.sharedCandidates.textContent.includes('인터플렉스'));vm.runInContext(`choose(watch.find(c=>c.id==='005930'),'8542321010')`,ctx);assert(els.scopeNotice.textContent.includes('854232'));assert(els.scopeNotice.textContent.includes('참고지표'));vm.runInContext(`choose(watch.find(c=>c.id==='005930'),'8542')`,ctx);assert(els.scopeNotice.textContent.includes('조회할 수 없습니다'));els.companySearch.value='반도체';vm.runInContext('renderUniverse()',ctx);assert(els.companyList.children.length<40);els.download.onclick();vm.runInContext(`const saved=backlog; const c=watch.find(c=>c.id==='222800'); renderBacklog(c); if(charts.backlog.data.datasets[0].data[charts.backlog.data.labels.indexOf('2026-Q2')]!==392.355)throw Error('USD conversion'); backlog=backlog.filter(r=>!(r.company_id==='222800'&&r.period==='2026-Q1')); renderBacklog(c); if(charts.backlog.data.datasets[0].data[charts.backlog.data.labels.indexOf('2026-Q1')]!==null)throw Error('Missing quarter filled or collapsed'); backlog=saved; renderBacklog(watch.find(c=>c.id==='005930')); if(!el('backlog').hidden||!el('backlogEmpty').textContent.includes('비공개'))throw Error('Undisclosed value plotted');`,ctx);console.log('PASS: all companies, units, missing-quarter gaps, undisclosed values, existing chart selection paths');}catch(e){console.error(e);process.exitCode=1;}});
