name: Test API Key

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 파일 가져오기
        uses: actions/checkout@v4

      - name: Python 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: test.py 실행
        env:
          CUSTOMS_API_KEY: ${{ secrets.CUSTOMS_API_KEY }}
        run: python test.py
